# CLI commands:
# - docker-compose up -d --build

version: '3.3'

services:

  backend:
    build:
      context: ./backend
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: bash ./scripts/start.sh
    volumes:
      - ./backend:/app
    restart: on-failure

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 4321:${POSTGRES_PORT}
    volumes: 
      - db_data:/var/lib/postgresql/data/

volumes:
    db_data: {}